# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

[BlueprintSettings]
kde/pim/mimetreeparser.version=master
kde/pim/kmime.version=master
kde/pim/kmbox.version=master
kde/pim/libkleo.version=master
kde/pim/kleopatra.version=master
