# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kiconthemes': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/kxmlgui': '@latest'
    'pim/kmime' : 'release/23.08'
    'pim/libkleo' : '@same'
    'pim/kidentitymanagement' : 'release/23.08'
    'pim/kmailtransport' : 'release/23.08'
    'pim/mimetreeparser' : 'kf5'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
