# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/kmime': '@same'
    'pim/libkleo': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'pim/mimetreeparser': '@same'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD']
  xml-validate-include:
  - src/kleopatra.w32-manifest.in
  cppcheck-arguments: '--enable=warning,style,performance -DKDAB_SYNCHRONIZED -DKLEOPATRA_VERSION_STRING=\"1.2.3\" -DQ_DISABLE_COPY_MOVE -DHAVE_QDBUS --suppress-xml=cppcheck-suppressions.xml'
  cppcheck-ignore-files:
  - autotests
  - tests
